title: Jason Brown
logo: "/jason.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Python/Intelligent Automation Engineer
  <br><br>
  
  <a href="mailto:jasondexterbrown@gmail.com">jasondexterbrown@gmail.com</a>
  <br>
  
  <a href="https://www.linkedin.com/in/jasondexterbrown/">LinkedIn Profile</a>
  <br><br>
  Python Projects
    <a href="https://github.com/JdexterBrown</a>
  
  <br>
 
  
   
theme: jekyll-theme-dinky
